/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marshaPlusSol from "./MarshaPlus.sol";
export type { marshaPlusSol };
import type * as voterMarshaSol from "./Voter-Marsha.sol";
export type { voterMarshaSol };
import type * as chatGpt from "./chatGpt";
export type { chatGpt };
