/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mainSol from "./main.sol";
export type { mainSol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
import type * as voitingSol from "./voiting.sol";
export type { voitingSol };
