/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as marshaPlusSol from "./MarshaPlus.sol";
export * as voterMarshaSol from "./Voter-Marsha.sol";
export * as chatGpt from "./chatGpt";
