/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mainSol from "./main.sol";
export * as nftSol from "./nft.sol";
export * as stakingSol from "./staking.sol";
export * as voitingSol from "./voiting.sol";
